<?php

/**
 * Implements hook_hosting_tasks().
 */
function hosting_git_checkout_hosting_tasks() {
  $tasks = array();

  $tasks['site']['git-checkout'] = array(
    'title' => t('Git checkout'),
    'description' => t('Runs a git checkout on the current site.'),
    'access callback' => 'hosting_git_checkout_access_checkout',
    'dialog' => TRUE,
  );

  $tasks['platform']['git-checkout'] = array(
    'title' => t('Git checkout'),
    'description' => t('Runs a git checkout on the current platform.'),
    'access callback' => 'hosting_git_checkout_access_checkout',
    'dialog' => TRUE,
  );

  return $tasks;
}

/**
 * Access function for the checkout task on platforms.
 */
function hosting_git_checkout_access_checkout($node) {
  // Only consider doing this if we have a git repo.
  if (empty($node->git['repo_url'])) {
    return FALSE;
  }
  if (($node->type == 'site' && user_access('create site git-checkout task'))
    || ($node->type == 'platform' && user_access('create platform git-checkout task'))) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Implements hook_permission().
 */
function hosting_git_checkout_permission() {
  return array(
    'create site git-checkout task' => array(
      'title' => t('create site git-checkout task'),
      'description' => t('Create a git-checkout task for sites'),
    ),
    'create platform git-checkout task' => array(
      'title' => t('create platform git-checkout task'),
      'description' => t('Create a git-checkout task for platforms'),
    ),
  );
}

/**
 * Implements hook_form().
 */
function hosting_task_git_checkout_form($node) {

  $form['git_ref'] = array(
    '#title' => t('Git Branch, tag, or hash'),
    '#description' => t("Check out this branch, tag, or hash."),
    '#type' => 'textfield',
    '#weight' => '-2',
    '#default_value' => isset($_GET['checkout_git_ref'])? $_GET['checkout_git_ref']: '',
  );

  $form['branch'] = array(
    '#title' => t('Create a new branch.'),
    '#description' => t("Use the '-b' option to create a new branch."),
    '#type' => 'checkbox',
    '#weight' => '-1',
    '#default_value' => TRUE,
  );

  $form['push'] = array(
    '#title' => t('Push the new branch.'),
    '#description' => t("Push the new branch to the remote repository."),
    '#type' => 'checkbox',
    '#weight' => '-1',
    '#default_value' => TRUE,
  );

  $form['reset_hard'] = array(
    '#title' => t('Force: Reset --hard before checkout?'),
    '#description' => t("Uncommitted changes will be lost."),
    '#type' => 'checkbox',
    '#weight' => '-1',
    '#default_value' => TRUE,
  );

  return $form;
}

/**
 * Implements hook_form_alter().
 */
function hosting_git_checkout_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'hosting_task_confirm_form' && $form['task']['#value'] == 'git-checkout') {
    drupal_set_title(t('Create or checkout a git branch'));
    $form['actions']['submit']['#value'] = t('Checkout Branch');
  }
}
